//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testSQLConnection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aves
    {
        public int ID { get; set; }
        public string waypoint { get; set; }
        public Nullable<System.DateTime> eventTime { get; set; }
        public string 資料行_3 { get; set; }
        public string vernacularName { get; set; }
        public Nullable<int> individualCount { get; set; }
        public Nullable<double> decimalLatitude { get; set; }
        public Nullable<double> decimalLongitude { get; set; }
        public Nullable<double> detectionDistance { get; set; }
        public Nullable<double> flightHeight { get; set; }
        public string flightDirection { get; set; }
        public string weather { get; set; }
        public string sightability { get; set; }
        public string visibility { get; set; }
        public string behavior { get; set; }
        public string note { get; set; }
        public string observer { get; set; }
        public string noteTaker { get; set; }
        public string photographer { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public string vessel { get; set; }
        public string route { get; set; }
        public string observingSide { get; set; }
        public string fieldOfVision { get; set; }
        public string lastHighTide { get; set; }
        public string lastLowTide { get; set; }
        public string windForce { get; set; }
        public string windDirection { get; set; }
        public string effort { get; set; }
    }
}
